from enum import StrEnum


class EventType(StrEnum):
    DEPOSIT_CREATED = "DEPOSIT_CREATED"
    MONEY_DEBITED = "MONEY_DEBITED"
    TRANSFER_COMPLETED = "TRANSFER_COMPLETED"
    FUNDS_CREDITED = "FUNDS_CREDITED"


class ReconciliationStatus(StrEnum):
    PENDING = "PENDING"
    MATCHED = "MATCHED"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    DATA_MISMATCH = "DATA_MISMATCH"
    INVALID_SEQUENCE = "INVALID_SEQUENCE"